version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Database=appdb;Username=appuser;Password=apppassword
    ports:
      - "5000:8080"

volumes:
  pgdata: